#
# This file is part of GreatFET
#

execute_process(
	COMMAND dfu-suffix -V
	WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}
	RESULT_VARIABLE DFU_NOT_FOUND
	ERROR_QUIET
	OUTPUT_VARIABLE DFU_VERSION_STRING
	OUTPUT_STRIP_TRAILING_WHITESPACE
)

set(DFU_ALL "")
if(NOT DFU_NOT_FOUND)
    set(DFU_ALL "ALL")
else(NOT DFU_NOT_FOUND)
	MESSAGE(STATUS "dfu-suffix not found: not building DFU file")
endif(NOT DFU_NOT_FOUND)

